/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as PluginRouteImport } from './routes/plugin'
import { Route as StylesRouteImport } from './routes/styles'
import { Route as ApiAiUiRouteImport } from './routes/api/ai-ui'
import { Route as ApiPublicSyncRouteImport } from './routes/api/public/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginRoute = PluginRouteImport.update({
  id: '/plugin',
  path: '/plugin',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesRoute = StylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiUiRoute = ApiAiUiRouteImport.update({
  id: '/api/ai-ui',
  path: '/api/ai-ui',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncRoute = ApiPublicSyncRouteImport.update({
  id: '/api/public/sync',
  path: '/api/public/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/plugin': typeof PluginRoute
  '/styles': typeof StylesRoute
  '/api/ai-ui': typeof ApiAiUiRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/plugin': typeof PluginRoute
  '/styles': typeof StylesRoute
  '/api/ai-ui': typeof ApiAiUiRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/plugin': typeof PluginRoute
  '/styles': typeof StylesRoute
  '/api/ai-ui': typeof ApiAiUiRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/builder' | '/plugin' | '/styles' | '/api/ai-ui' | '/api/public/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/builder' | '/plugin' | '/styles' | '/api/ai-ui' | '/api/public/sync'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/plugin'
    | '/styles'
    | '/api/ai-ui'
    | '/api/public/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  PluginRoute: typeof PluginRoute
  StylesRoute: typeof StylesRoute
  ApiAiUiRoute: typeof ApiAiUiRoute
  ApiPublicSyncRoute: typeof ApiPublicSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugin': {
      id: '/plugin'
      path: '/plugin'
      fullPath: '/plugin'
      preLoaderRoute: typeof PluginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles': {
      id: '/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-ui': {
      id: '/api/ai-ui'
      path: '/api/ai-ui'
      fullPath: '/api/ai-ui'
      preLoaderRoute: typeof ApiAiUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync': {
      id: '/api/public/sync'
      path: '/api/public/sync'
      fullPath: '/api/public/sync'
      preLoaderRoute: typeof ApiPublicSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  PluginRoute: PluginRoute,
  StylesRoute: StylesRoute,
  ApiAiUiRoute: ApiAiUiRoute,
  ApiPublicSyncRoute: ApiPublicSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
